version = 1

[[analyzers]]
name = "solhint"
type = "community"

[[analyzers]]
name = "slither"
type = "community"

[[analyzers]]
name = "kube-linter"
type = "community"

[[analyzers]]
name = "dart-analyze"
type = "community"

[[analyzers]]
name = "cfn-lint"
type = "community"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "javascript"